[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault_2024 = "DwLmZCpPDvnSSYRojAPNXnWBcpbp5kgPpVqqmdDMo9Zk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nielsoskam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
